version: '3.8'

services:
    firebase-firestore:
        container_name: firebase-firestore
        image: node:16-alpine3.12
        env_file: .env
        working_dir: /src
        volumes:
            - .:/src
        command:
            - /bin/sh
            - -c
            - |
                npm i
                sleep infinity